version: '3.5'

services:
  gc-ml-api:
    container_name: "${COMPOSE_PROJECT_NAME:-gc-dev}-gc-ml-api"
    build:
      context: "../"
      dockerfile: "devtools/docker/gc_ml_api/Dockerfile"
    environment:
      WORKER_COUNT: "${GC_ML_API_WORKER_COUNT:?}"
      FLASK_APP: "${GC_ML_API_FLASK_APP:?}"
      PYTHONUNBUFFERED: "${GC_ML_API_PYTHONUNBUFFERED:?}"
      FLASK_ENV: "${GC_ML_API_FLASK_ENV:?}"
      DOCKER_COMPOSE: "${GC_ML_API_DOCKER_COMPOSE:?}"
      AWS_SECRET_KEY: "${GC_ML_API_AWS_SECRET_KEY:?}"
      AWS_BUCKET_NAME: "${GC_ML_API_AWS_BUCKET_NAME:?}"
      AWS_ACCESS_KEY: "${GC_ML_API_AWS_ACCESS_KEY:?}"
      AWS_DEFAULT_REGION: "${GC_ML_API_AWS_DEFAULT_REGION:?}"
      ENV_TYPE: "${GC_ML_API_ENV_TYPE:?}"
      DATA_API_BASE_URL: "${GC_ML_API_DATA_API_BASE_URL:?}"
      GC_ML_API_MODEL_NAME: "${GC_ML_API_MODEL_NAME:?}"
      GC_ML_API_MODEL_PARENT_DIR: "${GC_ML_API_MODEL_PARENT_DIR:?}"

    image: "gc-ml-api:latest"
    ports:
      - "${GC_ML_API_FLASK_PORT:?}:${GC_ML_API_FLASK_PORT:?}"
    networks:
      - app-net

  gc-ml-redis:
    container_name: "${COMPOSE_PROJECT_NAME:-gc-dev}-gc-ml-redis"
    image: "redis:latest"
    ports:
      - "${GC_ML_API_REDIS_PORT:?}:${GC_ML_API_REDIS_PORT:?}"
    networks:
      - app-net


networks:
  app-net:
    name: "${COMPOSE_PROJECT_NAME:-gc-dev}-network"